[[Git_LFS]]
arch = "aarch64"
git-tree-sha1 = "ed001e2f6c00c27411bdad1c2868c1dd40625488"
os = "macos"

    [[Git_LFS.download]]
    sha256 = "48102c81745a6605506374d9e5525576e014e886715213684cd8888a05cb70dd"
    url = "https://github.com/JuliaBinaryWrappers/Git_LFS_jll.jl/releases/download/Git_LFS-v3.7.1+0/Git_LFS.v3.7.1.aarch64-apple-darwin.tar.gz"
[[Git_LFS]]
arch = "aarch64"
git-tree-sha1 = "18007b16acffed0d904d9479a7737b7b03b2223d"
libc = "glibc"
os = "linux"

    [[Git_LFS.download]]
    sha256 = "53c24d9ec22a5f42526326d7c9405192281f6ee60923e5efb87cc5b15b8c7c13"
    url = "https://github.com/JuliaBinaryWrappers/Git_LFS_jll.jl/releases/download/Git_LFS-v3.7.1+0/Git_LFS.v3.7.1.aarch64-linux-gnu.tar.gz"
[[Git_LFS]]
arch = "aarch64"
git-tree-sha1 = "18007b16acffed0d904d9479a7737b7b03b2223d"
libc = "musl"
os = "linux"

    [[Git_LFS.download]]
    sha256 = "53c24d9ec22a5f42526326d7c9405192281f6ee60923e5efb87cc5b15b8c7c13"
    url = "https://github.com/JuliaBinaryWrappers/Git_LFS_jll.jl/releases/download/Git_LFS-v3.7.1+0/Git_LFS.v3.7.1.aarch64-linux-musl.tar.gz"
[[Git_LFS]]
arch = "aarch64"
git-tree-sha1 = "128025e30498ee5312813ec4c8da4373d71ccfdb"
os = "freebsd"

    [[Git_LFS.download]]
    sha256 = "7bf14cf5956dca77739d203681a9affb381e6c9a1b240297c63d57bd59ddcf30"
    url = "https://github.com/JuliaBinaryWrappers/Git_LFS_jll.jl/releases/download/Git_LFS-v3.7.1+0/Git_LFS.v3.7.1.aarch64-unknown-freebsd.tar.gz"
[[Git_LFS]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "20c5e6d4a48e17d5702d707679a01604c3cebbd1"
libc = "glibc"
os = "linux"

    [[Git_LFS.download]]
    sha256 = "f79dcc53e6b873054c439d31f57315b13a3a6ca0360f127e9b2b97592691581d"
    url = "https://github.com/JuliaBinaryWrappers/Git_LFS_jll.jl/releases/download/Git_LFS-v3.7.1+0/Git_LFS.v3.7.1.armv6l-linux-gnueabihf.tar.gz"
[[Git_LFS]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "20c5e6d4a48e17d5702d707679a01604c3cebbd1"
libc = "musl"
os = "linux"

    [[Git_LFS.download]]
    sha256 = "f79dcc53e6b873054c439d31f57315b13a3a6ca0360f127e9b2b97592691581d"
    url = "https://github.com/JuliaBinaryWrappers/Git_LFS_jll.jl/releases/download/Git_LFS-v3.7.1+0/Git_LFS.v3.7.1.armv6l-linux-musleabihf.tar.gz"
[[Git_LFS]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "d279343b3c1c0acd46646ff5e997749990a9f77f"
libc = "glibc"
os = "linux"

    [[Git_LFS.download]]
    sha256 = "fb46cfdf46e719519218d2d5b312008d4a6b809d8443b267e7f3c9292498a336"
    url = "https://github.com/JuliaBinaryWrappers/Git_LFS_jll.jl/releases/download/Git_LFS-v3.7.1+0/Git_LFS.v3.7.1.armv7l-linux-gnueabihf.tar.gz"
[[Git_LFS]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "d279343b3c1c0acd46646ff5e997749990a9f77f"
libc = "musl"
os = "linux"

    [[Git_LFS.download]]
    sha256 = "fb46cfdf46e719519218d2d5b312008d4a6b809d8443b267e7f3c9292498a336"
    url = "https://github.com/JuliaBinaryWrappers/Git_LFS_jll.jl/releases/download/Git_LFS-v3.7.1+0/Git_LFS.v3.7.1.armv7l-linux-musleabihf.tar.gz"
[[Git_LFS]]
arch = "i686"
git-tree-sha1 = "9cc953beb8202df7e713cf8141ca1982216cb06a"
libc = "glibc"
os = "linux"

    [[Git_LFS.download]]
    sha256 = "e0d6982ebd0c4718a958787285b745f49496b315134b6577a027ed55d0d41365"
    url = "https://github.com/JuliaBinaryWrappers/Git_LFS_jll.jl/releases/download/Git_LFS-v3.7.1+0/Git_LFS.v3.7.1.i686-linux-gnu.tar.gz"
[[Git_LFS]]
arch = "i686"
git-tree-sha1 = "9cc953beb8202df7e713cf8141ca1982216cb06a"
libc = "musl"
os = "linux"

    [[Git_LFS.download]]
    sha256 = "e0d6982ebd0c4718a958787285b745f49496b315134b6577a027ed55d0d41365"
    url = "https://github.com/JuliaBinaryWrappers/Git_LFS_jll.jl/releases/download/Git_LFS-v3.7.1+0/Git_LFS.v3.7.1.i686-linux-musl.tar.gz"
[[Git_LFS]]
arch = "i686"
git-tree-sha1 = "1b8c4b2ecf9311bbd9f8197ead2be6c2aeef5568"
os = "windows"

    [[Git_LFS.download]]
    sha256 = "d597a01dfd4cad963cf191e51128ed3a571d807012394d039ea2f024c6b93866"
    url = "https://github.com/JuliaBinaryWrappers/Git_LFS_jll.jl/releases/download/Git_LFS-v3.7.1+0/Git_LFS.v3.7.1.i686-w64-mingw32.tar.gz"
[[Git_LFS]]
arch = "powerpc64le"
git-tree-sha1 = "99ecbe16865807139837c039dce1b565b27ae924"
libc = "glibc"
os = "linux"

    [[Git_LFS.download]]
    sha256 = "84b400a6d3e40caee0210c025334ac44faf51cf6deaaa47ed1530609021d6909"
    url = "https://github.com/JuliaBinaryWrappers/Git_LFS_jll.jl/releases/download/Git_LFS-v3.7.1+0/Git_LFS.v3.7.1.powerpc64le-linux-gnu.tar.gz"
[[Git_LFS]]
arch = "riscv64"
git-tree-sha1 = "a30410589ea961b7e7b88152124b26be196dde56"
libc = "glibc"
os = "linux"

    [[Git_LFS.download]]
    sha256 = "dff8ded3bbf930f672e2b9195628d1e5e896403c8a506fbffd7da9f71718e6d9"
    url = "https://github.com/JuliaBinaryWrappers/Git_LFS_jll.jl/releases/download/Git_LFS-v3.7.1+0/Git_LFS.v3.7.1.riscv64-linux-gnu.tar.gz"
[[Git_LFS]]
arch = "x86_64"
git-tree-sha1 = "fc3c7d464c70aba14cb138de834003ba9164cc23"
os = "macos"

    [[Git_LFS.download]]
    sha256 = "7ebf99b093735fa2745791a4b23a226dda0c5e225c4003fa595447bbc591b69c"
    url = "https://github.com/JuliaBinaryWrappers/Git_LFS_jll.jl/releases/download/Git_LFS-v3.7.1+0/Git_LFS.v3.7.1.x86_64-apple-darwin.tar.gz"
[[Git_LFS]]
arch = "x86_64"
git-tree-sha1 = "cbc69e6685959a713544a0b78531d49cb0ef8154"
libc = "glibc"
os = "linux"

    [[Git_LFS.download]]
    sha256 = "5cd7706e9cdf04ea119977cbd32da588a8bb8c90ef4e3bd33cd95bc46235cb1e"
    url = "https://github.com/JuliaBinaryWrappers/Git_LFS_jll.jl/releases/download/Git_LFS-v3.7.1+0/Git_LFS.v3.7.1.x86_64-linux-gnu.tar.gz"
[[Git_LFS]]
arch = "x86_64"
git-tree-sha1 = "5469cc1c88f0ed259c8ff1e27dca7e00f99b1897"
libc = "musl"
os = "linux"

    [[Git_LFS.download]]
    sha256 = "860054bcabdccf7123721481a072027555d8912fea6386d68521091be064f1ba"
    url = "https://github.com/JuliaBinaryWrappers/Git_LFS_jll.jl/releases/download/Git_LFS-v3.7.1+0/Git_LFS.v3.7.1.x86_64-linux-musl.tar.gz"
[[Git_LFS]]
arch = "x86_64"
git-tree-sha1 = "407b2d6a1112f15186d59fdebe33c77aa9c669ed"
os = "freebsd"

    [[Git_LFS.download]]
    sha256 = "c8726d611f110a9498b7a2848ede57846b02841c7036b87a21d28c01006b2a73"
    url = "https://github.com/JuliaBinaryWrappers/Git_LFS_jll.jl/releases/download/Git_LFS-v3.7.1+0/Git_LFS.v3.7.1.x86_64-unknown-freebsd.tar.gz"
[[Git_LFS]]
arch = "x86_64"
git-tree-sha1 = "5a8045b25dc841cadf34f0a22adf4a6980ef4841"
os = "windows"

    [[Git_LFS.download]]
    sha256 = "25a029a07ceab2cf7e855677d326e9858e95d67512ac1be44a6b1b606b729103"
    url = "https://github.com/JuliaBinaryWrappers/Git_LFS_jll.jl/releases/download/Git_LFS-v3.7.1+0/Git_LFS.v3.7.1.x86_64-w64-mingw32.tar.gz"
