# Autogenerated wrapper script for Git_LFS_jll for x86_64-w64-mingw32
export git_lfs

JLLWrappers.@generate_wrapper_header("Git_LFS")
JLLWrappers.@declare_executable_product(git_lfs)
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_executable_product(
        git_lfs,
        "bin\\git-lfs.exe",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
